### ISSUE TITLE
Studio View for Scorm files is having cache issue.

### ISSUE THREAD

**Issue by bvenkatr** [overhangio/openedx-scorm-xblock#1]
I was experimenting with this lib and found that when we reupload **scorm_2.zip** file in same scorm component/unit in studio where **scorm_1.zip** was uploaded earlier, studio view is still showing/playing **scorm_1.zip** file content.

But when we **refresh browser** then it’s playing **scorm_2.zip** file content. It looks like there is some caching issue over there.

Here 2 sample file to test with
[Women_in_Sports_Digital_Mag  scorm 1.zip](https://github.com/overhangio/openedx-scorm-xblock/files/4547279/Women_in_Sports_Digital_Mag.scorm.1.zip)
[Quiz scorm 1.zip](https://github.com/overhangio/openedx-scorm-xblock/files/4547281/Quiz.scorm.1.zip)

**Comment by regisb** [comment]
This issue is due to the fact that nginx caches media files with a fixed expiration time. It's difficult to modify the expiration time just for scorm files, because the scorm file location may be customized by every user (see LOCATION xblock setting).

This is problematic because the root cause is at the core of the design of the xblock. We could solve this by making sure that the package file sha1 checksum be added to the media path, but that would break existing xblocks. Sill, I think we can keep backward-compatibility, but I need to investigate a little further.
