### ISSUE TITLE
Weight option missing in scorm unit

### ISSUE THREAD

**Issue by Balji** [overhangio/openedx-scorm-xblock#2]
Hello,
I have installed this scorm xblock in my open edx instance.
I have set subsection as graded and when I add scorm unit, there is no "Weight" column available.

Can you please help !!

Thanks

**Comment by regisb** [comment]
Hi @Balji! Indeed, currently there is no way to modify the xblock weight attribute. This is a missing feature. I'm currently looking into fixing this. Would you be so kind as to send me a minimal scorm package example (zip file), just with some basic questions, so that I could test its integration with this xblock?

**Comment by regisb** [comment]
This should be closed by 18cc13e8f6ed9cf872959718eaf2c9e85421d905
